name: pokerhome-app
recipe: laravel
config:
  php: '8.1'
  webroot: public
  via: apache
  database: mysql:5.7
  xdebug: true
services:
  myservice:
    type: node
tooling:
  node:
    service: myservice
  npm:
    service: myservice